config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  devise_scope :users do
    get '/login' => 'devise/sessions#new'
    get '/salir' => 'devise/sessions#destroy'
  end
  root :to => "static#index"
  get 'index' => "static#index2"

  get 'la-propuesta' => 'static#our_story', as: 'our_story'
  get 'informacion' => 'static#info', as: 'info'
  
  resources :users, only: [:show, :edit]
  get 'mi-cuenta' => 'users#show', as: 'my_account'

  resources :hotels, path: 'hoteles', only: [:index, :show] do
    resources :rooms, path: 'habitaciones', only: [:index, :show]
  end
  resources :galleries, path: 'galerias', only: [:index, :show]

  resources :photos, only: [] do
    collection do
      get :tags
    end
  end

  get 'oauth/callback' => 'photos#callback'
  get 'oauth/connect' => 'photos#connect'

  get 'admin' => 'admin#dashboard'

  get 'static/index'

  namespace :admin do
    resources :users
    resources :hotels do
      resources :rooms
    end
    resources :galleries
    resources :orders do
      put :pay, on: :member
      delete 'destroy_payment/:id' => 'orders#destroy_payment', as: 'destroy'
    end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
  has_many :payments

  validates_presence_of :room, :user

  before_save :validate_data

  def total_amount
    @total = room.price * total_guests * days
    @total = @total + (kids*800 * days) if !kids.nil? && kids > 0
    @total = @total - discount_total if !discount.nil? && discount > 0
    return 0 if @total.nil?
    return @total
  end

  def discount_total
    if discount_type == 'percent'
      (room.price * total_guests * days)/100 * discount
    else
      discount
    end
  end

  def total_paid
    payments.sum(:amount) || paid || 0
  end

  def total_guests
    return qty - kids if kids > 0
    qty
  end

  def validate_data
    self.discount = 0 if discount.nil?
    self.kids = 0 if kids.nil?
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_filter :set_order, only: [:show, :edit, :update, :destroy, :pay]
  before_filter :set_rooms, only: [:new, :edit]
  layout 'admin'
  include ActionView::Helpers::NumberHelper

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end
  
    # GET /orders/new
  def new
    @order = Order.new(user_id: params[:user_id])
  end

  # GET /orders/1/edit
  def edit
  end

  def pay
    @payment = @order.payments.new(payment_params)
    respond_to do |format|
      if @payment.save
        format.html { redirect_to admin_order_path, notice: 'Pago registrado.' }
        format.js { render :pay }
      else
        format.html { render :show }
        format.js { render :pay }
      end
    end
  end

  def destroy_payment
    @payment = Payment.find(params[:id])
    @order=Order.find(params[:order_id])
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to admin_user_url(@order.user), notice: 'Pago eliminado.' }
      format.json { head :no_content }
    end
  end

  # POST /orders
  # POST /orders.json
  def create
    user = User.find(params[:order][:user_id])
    @order = Order.new(order_params)
    user.order = @order
    user.save!

    respond_to do |format|
      if @order.save
        format.html { redirect_to admin_users_path, notice: 'order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to admin_users_path, notice: 'order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to admin_hotel_order_url(@order), notice: 'order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    def set_rooms
      @rooms_available = Room.all.collect{|r| ["#{r.name} - #{number_to_currency(r.price)}", r.id] }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :qty, :discount, :discount_type, :room_id, :kids, :days, :paid)
    end

    def payment_params
      params.require(:payment).permit(:amount, :payment_type)
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/_form.html.haml
= form_for @order, url: (@order.persisted? ? admin_order_path(@order) : admin_orders_path), html: { class: 'form-horizontal', role: 'form' } do |f|
  - if @order.errors.any?
    #error_explanation
      %h2= "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      %ul
        - @order.errors.full_messages.each do |msg|
          %li= msg
  = f.hidden_field :user_id
  .form-group
    = f.label :qty, 'Habitacion', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.select :room_id, options_for_select(@rooms_available, selected: @order.room_id), {prompt: 'Selecciona una habitacion'}, class: 'form-control'
  .form-group
    = f.label :qty, 'Numero de huespedes', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :qty, placeholder: 'Numero de huespedes', class: 'form-control'
  .form-group
    = f.label :days, 'Dias/Noches', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :days, placeholder: 'Numero de dias', class: 'form-control'
  .form-group
    = f.label :kids, 'Menores?', class: 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :kids, placeholder: 'Menores', class: 'form-control'
  .form-group
    = f.label :discount, 'Descuento', class: 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :discount, placeholder: 'Descuento', class: 'form-control'
    .col-sm-6
      = f.radio_button :discount_type, 'percent'
      = f.label :discount_type_percent, 'Porcentaje', class: 'control-label'
      = f.radio_button :discount_type, 'amount'
      = f.label :discount_type_amount, 'Efectivo', class: 'control-label'
  .form-group
    = f.label :paid, 'Abono', class: 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :paid, placeholder: 'Total pagado', class: 'form-control'
  .form-group
    .col-sm-10.col-sm-offset-2
      = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/orders/_pay_form.html.haml
= form_for Payment.new, url: pay_admin_order_path(@user ? @user.order : @order), method: :put, html: { id: 'payment_form', class: 'form-horizontal', role: 'form' }, remote: true do |f|
  #payment_error_explanation
  .form-group
    = f.label :amount, 'Monto', class: 'col-sm-4 control-label'
    .col-sm-8
      = f.text_field :amount, placeholder: 'Monto', class: 'form-control'
  .form-group
    = f.label :payment_type, 'Forma de pago', class: 'col-sm-4 control-label'
    .col-sm-8
      = f.text_field :payment_type, placeholder: 'Forma de pago', class: 'form-control'
  .form-group
    .col-sm-8.col-sm-offset-4
      = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/orders/edit.html.haml
= render 'form'

app/views/admin/orders/index.html.haml
%h1.page-header Ordenes
.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th 
        %th 
        %th 
        %th 
        %th
        %th
        %th
    %tbody
      - @orders.each do |order|
        %tr
          %td= order.id
          %td= order.last_name
          %td= order.email
          %td= order.password
          %td= link_to 'Show', order
          %td= link_to 'Edit', edit_order_path(order)
          %td= link_to 'Destroy', order, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

  = link_to 'New User', new_admin_order_path

app/views/admin/orders/new.html.haml
= render 'form'

app/views/admin/orders/pay.js.haml
- if @payment.errors.any?
  $('#payment_error_explanation').replaceWith("#{ j("<h2>#{pluralize(@payment.errors.count, 'error')} ha impedido guardar eset pago:</h2><ul>#{@payment.errors.full_messages.each{|msg| "<li>#{msg}</li>"};nil }</ul>").html_safe}" );
- else
  $('#payment').collapse('hide');
  $("#payments table tbody").append("#{j("<tr><td>#{number_to_currency(@payment.amount)}</td><td>#{@payment.payment_type}</td></tr>").html_safe}");
  $('.total-payments').text("#{number_to_currency(@payment.order.total_paid)}");
  $('#payment_form').replaceWith("#{escape_javascript(render 'pay_form')}");