config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  devise_scope :users do
    get '/login' => 'devise/sessions#new'
    get '/salir' => 'devise/sessions#destroy'
  end
  root :to => "static#index"
  get 'index' => "static#index2"

  get 'la-propuesta' => 'static#our_story', as: 'our_story'
  get 'informacion' => 'static#info', as: 'info'
  
  resources :users, only: [:show, :edit]
  get 'mi-cuenta' => 'users#show', as: 'my_account'

  resources :hotels, path: 'hoteles', only: [:index, :show] do
    resources :rooms, path: 'habitaciones', only: [:index, :show]
  end
  resources :galleries, path: 'galerias', only: [:index, :show]

  resources :photos, only: [] do
    collection do
      get :tags
    end
  end

  get 'oauth/callback' => 'photos#callback'
  get 'oauth/connect' => 'photos#connect'

  get 'admin' => 'admin#dashboard'

  get 'static/index'

  namespace :admin do
    resources :users
    resources :hotels do
      resources :rooms
    end
    resources :galleries
    resources :orders do
      put :pay, on: :member
      delete 'destroy_payment/:id' => 'orders#destroy_payment', as: 'destroy'
    end
  end

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  has_many :rooms
end

app/controllers/admin/hotels_controller.rb
class Admin::HotelsController < ApplicationController
  before_filter :set_hotel, only: [:show, :edit, :update, :destroy]
  layout 'admin'

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  def show
  end
  
    # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to admin_hotel_path(@hotel), notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:name, :price)
    end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :rooms]
  before_action :authenticate_user!

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  def rooms
    @rooms = @hotel.rooms
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

end

app/helpers/admin/hotels_helper.rb
module Admin::HotelsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/admin/hotels/_form.html.haml
= form_for @hotel, url: admin_hotels_path, html: { class: 'form-horizontal', role: 'form' } do |f|
  - if @hotel.errors.any?
    #error_explanation
      %h2= "#{pluralize(@hotel.errors.count, "error")} prohibited this hotel from being saved:"
      %ul
        - @hotel.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price
    = f.number_field :price
  .actions
    = f.submit 'Save'

app/views/admin/hotels/index.html.haml
%h1.page-header Hoteles
.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th Nombre
        %th 
        %th 
        %th 
        %th
        %th
        %th
    %tbody
      - @hotels.each do |hotel|
        %tr
          %td= hotel.name
          %td= link_to 'Mostrar', admin_hotel_path(hotel)
          %td= link_to 'Editar', edit_admin_hotel_path(hotel)
          %td= link_to 'Borrar', hotel, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

  = link_to 'New hotel', new_admin_hotel_path

app/views/admin/hotels/new.html.haml
%h1 Nuevo Hotel

= render 'form'

= link_to 'Regresar', hotels_path

app/views/admin/hotels/show.html.haml
.well
  %h1=@hotel.name

  .table-responsive
    %table.table.table-striped
      %thead
        %tr
          %th Nombre
          %th Descripcion
          %th Precio
          %th Capacidad
          %th Vista de la habitacion
          %th Servicios
          %th Hora de entrada
          %th Hora de salida
          %th Acciones
      %tbody
        - @hotel.rooms.each do |room|
          %tr
            %td= link_to room.name, admin_hotel_room_path(hotel_id: @hotel.id, id: room.id)
            %td= room.description
            %td= number_to_currency(room.price)
            %td= room.cap
            %td= room.room_view
            %td= room.services
            %td= room.start_time.strftime('%r') rescue ''
            %td= room.end_time.strftime('%r') rescue ''
            %td
              = link_to edit_admin_hotel_room_path(id: room.id, hotel_id: @hotel.id), title: 'Editar' do
                %span.glyphicon.glyphicon-pencil
              = link_to admin_hotel_room_path(id: room.id, hotel_id: @hotel.id), title: 'Borrar', :method => :delete, :data => { :confirm => 'Estas seguro?' } do
                %span.glyphicon.glyphicon-remove
  %br
  = link_to 'Agregar Habitacion', new_admin_hotel_room_path(hotel_id: @hotel.id)