config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  devise_scope :users do
    get '/login' => 'devise/sessions#new'
    get '/salir' => 'devise/sessions#destroy'
  end
  root :to => "static#index"
  get 'index' => "static#index2"

  get 'la-propuesta' => 'static#our_story', as: 'our_story'
  get 'informacion' => 'static#info', as: 'info'
  
  resources :users, only: [:show, :edit]
  get 'mi-cuenta' => 'users#show', as: 'my_account'

  resources :hotels, path: 'hoteles', only: [:index, :show] do
    resources :rooms, path: 'habitaciones', only: [:index, :show]
  end
  resources :galleries, path: 'galerias', only: [:index, :show]

  resources :photos, only: [] do
    collection do
      get :tags
    end
  end

  get 'oauth/callback' => 'photos#callback'
  get 'oauth/connect' => 'photos#connect'

  get 'admin' => 'admin#dashboard'

  get 'static/index'

  namespace :admin do
    resources :users
    resources :hotels do
      resources :rooms
    end
    resources :galleries
    resources :orders do
      put :pay, on: :member
      delete 'destroy_payment/:id' => 'orders#destroy_payment', as: 'destroy'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_uniqueness_of :email
  validates_presence_of :first_name, :last_name, :email, :control_id

  has_one :order

  # def admin?
  #   self.admin
  # end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource except: [:create]
  layout 'admin'

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @action = :post
  end

  # GET /users/1/edit
  def edit
    @action = :put
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: 'User was successfully created.' }
        format.json { render :nothing, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :control_id)
    end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :check_permissions, :only => [:new, :create, :cancel]
  skip_before_filter :require_no_authentication

  def check_permissions
    authorize! :create, resource
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /users/1
  # GET /users/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id]) rescue current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.haml
= form_for @user, url: (@user.persisted? ? admin_user_path(@user) : admin_users_path), html: { class: 'form-horizontal', role: 'form' } do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :first_name, 'Nombre', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :first_name, placeholder: 'Nombre', class: 'form-control'
  .form-group
    = f.label :last_name, 'Apellido', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :last_name, placeholder: 'Apellido', class: 'form-control'
  .form-group
    = f.label :control_id, 'Numero de control', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :control_id, placeholder: 'Numero de control', class: 'form-control'
  .form-group
    = f.label :email, 'Correo Electronico', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.email_field :email, placeholder: 'E-mail', class: 'form-control'
  - if !@user.persisted?
    .form-group
      = f.label :password, 'Contrasena', class: 'col-sm-2 control-label'
      .col-sm-10
        = f.password_field :password, placeholder: 'Contrasena', class: 'form-control'
  .form-group
    .col-sm-10.col-sm-offset-2
      = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', admin_users_path

app/views/admin/users/index.html.haml
%h1.page-header Usuarios
.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th Numero de control
        %th Nombre
        %th Email
        %th Habitacion
        %th Total
        %th Pagado
        %th Acciones
    %tbody
      - @users.each do |user|
        %tr
          %td= user.control_id
          %td= link_to user.full_name, admin_user_path(user)
          %td= user.email
          - if user.order
            %td= user.order.room.name
            %td= number_to_currency(user.order.total_amount)
            %td= number_to_currency(user.order.total_paid)
          - else
            %td
            %td
            %td
          %td
            = link_to admin_user_path(user), title: 'Mostrar usuario' do
              %span.glyphicon.glyphicon-user
            = link_to edit_admin_user_path(user), title: 'Editar' do
              %span.glyphicon.glyphicon-pencil
            = link_to admin_user_path(user), title: 'Borrar', :method => :delete, :data => { :confirm => 'Estas seguro?' } do
              %span.glyphicon.glyphicon-remove

  %br

  = link_to 'Agregar Usuario', new_admin_user_path

app/views/admin/users/new.html.haml
%h1 Nuevo usuario

= render 'form'

= link_to 'Regresar', admin_users_path

app/views/admin/users/show.html.haml
%h2
  = @user.full_name
  %small= @user.email

.well
  %div
    - if order = @user.order
      %p
        %b Habitacion
        %br
        = order.room.name
        -
        (#{order.room.price})
        %br
        = "#{order.qty} personas"
        = "#{order.kids} menor(es)" if order.kids
      %p
        %b Cuenta:
        %br
        = "Total: #{number_to_currency(order.total_amount)}"
        %br
        = "Descuento aplicado: #{number_to_currency(order.discount_total)}"
        %br
        Pagado: 
        %span.total-payments= number_to_currency(order.total_paid)
        %br
        = "Saldo: #{number_to_currency(order.total_amount - order.total_paid)}"
      = link_to 'Editar orden', edit_admin_order_path(@user.order)
      %br
      %br
      .centered
        %b Pagos
        #payments.table-responsive
          %table.table.table-striped
            %thead
              %tr
                %th Monto
                %th Tipo de pago
                %th
            %tbody
              - order.payments.each do |payment|
                %tr
                  %td= number_to_currency(payment.amount)
                  %td= payment.payment_type
                  %td
                    = link_to admin_order_destroy_path(order_id: order.id, id: payment.id), title: 'Borrar Pago', :method => :delete, :data => { :confirm => 'Estas seguro?' } do
                      %span.glyphicon.glyphicon-remove
          %p
            %b Total: 
            %span.total-payments
              #{number_to_currency(order.total_paid, unit: 'MX $')}

        = link_to 'Abonar', '#payment', data: { toggle: 'collapse' }
        .row.collapse#payment
          .col-sm-6
            = render 'admin/orders/pay_form'
    - else
      = link_to 'Agregar orden', new_admin_order_path(user_id: @user.id)