config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  devise_scope :users do
    get '/login' => 'devise/sessions#new'
    get '/salir' => 'devise/sessions#destroy'
  end
  root :to => "static#index"
  get 'index' => "static#index2"

  get 'la-propuesta' => 'static#our_story', as: 'our_story'
  get 'informacion' => 'static#info', as: 'info'
  
  resources :users, only: [:show, :edit]
  get 'mi-cuenta' => 'users#show', as: 'my_account'

  resources :hotels, path: 'hoteles', only: [:index, :show] do
    resources :rooms, path: 'habitaciones', only: [:index, :show]
  end
  resources :galleries, path: 'galerias', only: [:index, :show]

  resources :photos, only: [] do
    collection do
      get :tags
    end
  end

  get 'oauth/callback' => 'photos#callback'
  get 'oauth/connect' => 'photos#connect'

  get 'admin' => 'admin#dashboard'

  get 'static/index'

  namespace :admin do
    resources :users
    resources :hotels do
      resources :rooms
    end
    resources :galleries
    resources :orders do
      put :pay, on: :member
      delete 'destroy_payment/:id' => 'orders#destroy_payment', as: 'destroy'
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    if user.try(:admin?)
      admin_abilities(user)
    else
      user_abilities(user)
    end
  end

  def admin_abilities(user)
    if user.try(:admin?)
      can :manage, :all
    end
  end

  def user_abilities(user)
    can :read, Hotel
    can :read, Room
    can :show, User do |u|
      user == u
    end
    cannot [:create, :update], User
  end
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  has_many :rooms
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
  has_many :payments

  validates_presence_of :room, :user

  before_save :validate_data

  def total_amount
    @total = room.price * total_guests * days
    @total = @total + (kids*800 * days) if !kids.nil? && kids > 0
    @total = @total - discount_total if !discount.nil? && discount > 0
    return 0 if @total.nil?
    return @total
  end

  def discount_total
    if discount_type == 'percent'
      (room.price * total_guests * days)/100 * discount
    else
      discount
    end
  end

  def total_paid
    payments.sum(:amount) || paid || 0
  end

  def total_guests
    return qty - kids if kids > 0
    qty
  end

  def validate_data
    self.discount = 0 if discount.nil?
    self.kids = 0 if kids.nil?
  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :order

  validates_presence_of :amount
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :hotel 
  has_many :order
  mount_uploader :image, ImageUploader
end

app/models/room_image.rb
class RoomImage < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :room
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_uniqueness_of :email
  validates_presence_of :first_name, :last_name, :email, :control_id

  has_one :order

  # def admin?
  #   self.admin
  # end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  respond_to :html
  before_filter :authenticate_admin, :except => :login
  #load_and_authorize_resource User
  layout 'admin'

  def dashboard
    redirect_to admin_users_path
  end

  private 
  def authenticate_admin
    redirect_to '/users/sign_in' unless user_signed_in?

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = exception.message
    redirect_to root_url
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :authenticate_user!

  def index
    
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :rooms]
  before_action :authenticate_user!

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  def rooms
    @rooms = @hotel.rooms
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  CALLBACK_URL = "http://localhost:3000/oauth/callback"

  def connect
    url = Instagram.authorize_url(:redirect_uri => CALLBACK_URL)
    redirect_to url
  end

  def callback
    redirect_to '/photos'
  end

  def tags
    client = Instagram.client(:access_token => session[:access_token])
    tags = client.tag_search('LilianaIsaacBeachWedding2015')
    page = params.has_key?(:next_max_tag_id) ? params[:next_max_tag_id] : 0
    @photos = []
    if !tags.count.zero?
      @photos = page.to_i.zero? ? Instagram.tag_recent_media(tags[0].name) : Instagram.tag_recent_media(tags[0].name, :max_tag_id => params[:next_max_tag_id])
      @next_max_tag_id = @photos.pagination.next_max_tag_id
    end
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show]
  before_action :authenticate_user!

  def index
    @rooms = Room.all
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  layout 'homepage', only: :index
  before_action :authenticate_user!, except: [:index]
  
  def index
    return redirect_to index_path if user_signed_in?
  end

  def our_story
  end

  def info
  end

  def index2
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /users/1
  # GET /users/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id]) rescue current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin.html.haml
!!!html
%html
  %head
    %title Wedding
    = stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{ data: { toggle: 'collapse', target: '#navbar' }, aria: { expanded: 'false', controls: 'navbar' } }
            %span.sr-only Toggle Navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Isaac & Liliana', '#', class: 'navbar-brand'
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to 'Users', admin_users_path
            %li
              = link_to 'Gallery', galleries_path
            %li
              = link_to 'Info', '#'
            %li
              = link_to 'Ordenes', admin_orders_path
            - if user_signed_in?
              %li
                = link_to('Logout', destroy_user_session_path, :method => :delete)
            - else
              %li
                = link_to('Login', new_user_session_path)
    .container-fluid
      .col-sm-3.col-md-2.sidebar
        %ul.nav.nav-sidebar
          %li
            = link_to 'Usuarios', admin_users_path
          %li
            = link_to 'Ordenes', admin_orders_path
          %li
            = link_to 'Dreams Tulum', admin_hotel_path(1)
          %li
            = link_to 'Fotos', admin_galleries_path
      .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
        %p.notice
          = notice
        %p.alert
          = alert
        .container-fluid
          = yield

app/views/layouts/application.html.haml
!!!html
%html
  %head
    %title Boda - Liliana & Isaac
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    = csrf_meta_tags
  %body{ class: controller_name }
    - if controller_name != 'photos'
      %nav.navbar.navbar-inverse.navbar-fixed-top
        .container
          .navbar-header
            %button.navbar-toggle.collapsed{ data: { toggle: 'collapse', target: '#navbar' }, aria: { expanded: 'false', controls: 'navbar' } }
              %span.sr-only Toggle Navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
          #navbar.collapse.navbar-collapse
            %ul#nav.nav.navbar-nav
              - if controller_name == 'static'
                %li
                  = link_to 'La Propuesta', '#proposal'
                %li
                  = link_to 'Fotos', '#gallery'
                %li
                  = link_to 'Informacion', '#info'
              - else
                %li
                  = link_to 'Inicio', root_path
              - if user_signed_in?
                - if current_user.admin?
                  %li
                    = link_to 'Admin', admin_users_path
                -# else
                %li
                  = link_to 'Mi Cuenta', my_account_path
                %li
                  = link_to('Logout', destroy_user_session_path, :method => :delete)
              - else
                %li
                  = link_to('Login', new_user_session_path)
    %p.notice
      = notice
    %p.alert
      = alert
    #main-content.container-fluid
      = yield
    %footer.footer
      .container
        %p.text-muted
          Isaac & Liliana - 18.09.15
    = yield :javascript

app/views/layouts/homepage.html.haml
!!!html
%html
  %head
    %title Wedding
    = stylesheet_link_tag    'homepage', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %link{ href: 'http://fonts.googleapis.com/css?family=Petit+Formal+Script:400,700', rel: 'stylesheet', type: 'text/css' }
    %link{ href: 'http://fonts.googleapis.com/css?family=Slabo+27px', rel: 'stylesheet', type: 'text/css' }
    %link{ href: 'http://fonts.googleapis.com/css?family=Open+Sans:400,800,700', rel: 'stylesheet', type: 'text/css' }
    %link{ href: 'http://fonts.googleapis.com/css?family=Lato:400,700,900', rel: 'stylesheet', type: 'text/css' }
    = csrf_meta_tags
  %body.homepage
    .site-wrapper
      .site-wrapper-inner
        .cover-container
          .masthead.clearfix
            .inner
              %h3.masthead-brand 
              %ul.nav.masthead-nav
                %li
                  = link_to('Login', new_user_session_path)
          .inner.cover
            = yield
          .mastfoot
            .inner
              %p
                #countdown